-- SQL de Setup para Agente de Sincronização Firebird 2.5

-- 1. TABELAS_INTEGRADAS
-- Define quais tabelas devem ser monitoradas pelo agende de trace.
CREATE TABLE TABELAS_INTEGRADAS (
    NOME_TABELA VARCHAR(31) NOT NULL PRIMARY KEY,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N'))
);

-- 2. FILA_INTEGRACAO
-- Armazena os eventos capturados para processamento e envio.
CREATE TABLE FILA_INTEGRACAO (
    ID BIGINT NOT NULL PRIMARY KEY,
    EVENT_ID CHAR(36) NOT NULL,
    TABELA VARCHAR(31) NOT NULL,
    OPERACAO CHAR(1) NOT NULL, -- I: Insert, U: Update, D: Delete
    PK_JSON BLOB SUB_TYPE TEXT,
    PAYLOAD_JSON BLOB SUB_TYPE TEXT,
    ORIGEM VARCHAR(20),
    STATUS CHAR(1) DEFAULT 'P', -- P: Pendente, E: Enviado, A: Aplicado, R: Erro, F: Falha
    TENTATIVAS INTEGER DEFAULT 0,
    DT_EVENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_ULT_ENVIO TIMESTAMP,
    ERRO_MSG BLOB SUB_TYPE TEXT
);

-- Generator para o ID da Fila
CREATE GENERATOR GEN_FILA_INTEGRACAO_ID;

SET TERM ^ ;

-- Trigger para Auto-Incremento do ID
CREATE TRIGGER TRG_FILA_INTEGRACAO_BI FOR FILA_INTEGRACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR GEN_FILA_INTEGRACAO_ID;
END^

SET TERM ; ^

-- 3. Índices para performance
CREATE INDEX IDX_FILA_STATUS ON FILA_INTEGRACAO (STATUS);
CREATE UNIQUE INDEX IDX_FILA_EVENT_ID ON FILA_INTEGRACAO (EVENT_ID);

-- 4. Inserir exemplo de tabela (Opcional, apenas para referência)
-- INSERT INTO TABELAS_INTEGRADAS (NOME_TABELA, ATIVO) VALUES ('CLIENTES', 'S');
